### ISSUE TITLE
Latest version of dependency had a breaking change

### ISSUE THREAD

**Issue by justinmchase** [crqrdotcom/github_webhooks#1]
> error: TS2305 [ERROR]: Module '"https://deno.land/std@0.122.0/encoding/hex.ts"' has no exported member 'encodeToString'.
> export { encodeToString } from "https://deno.land/std/encoding/hex.ts";
>         ~~~~~~~~~~~~~~
>    at https://deno.land/x/github_webhooks@0.1.0/deps.ts:20:10

**Comment by justinmchase** [comment]
The last version to have this function was:

https://deno.land/std@0.100.0/encoding/hex.ts

**Comment by crqrdotcom** [comment]
Thanks for reporting this issue!

**Comment by crqrdotcom** [comment]
Fixed by #2. Thanks once more @justinmchase 

A new release with the fix is available: https://github.com/crqra/github_webhooks/releases/tag/0.1.1
